Manage EOL date by checkbox of  eol_explicit
snipe/snipe-it pull request #13846
Opened 2023-11-07 17:12 UTC by Robert-Azelis

# Description
[ It's re-created PR #13806 as I made mistake and update branch by master, sorry for confusion ]
This improvement allow setup EOL date manually by user on damand by set eol_explicit checkbox.

**BEFORE:**
![image](https://github.com/snipe/snipe-it/assets/82208283/4c9221ce-78a8-4c53-9575-f30634e53eba)

**AFTER:**
If checkbox is not checked then EOL date is hiden and calculation of date is on the base Model EOL rate
![image](https://github.com/snipe/snipe-it/assets/82208283/e0140b06-b105-474a-950c-5cc9e551888a)

If checkbox is checked then EOL date is showed and user can input EOL Date manually.
Status of checkbox is saved as eol_explicit value
![image](https://github.com/snipe/snipe-it/assets/82208283/468f9e12-5860-4052-b899-845b24e1d8d0)

In this way is much easier to manage EOL date and explicit marker status instead of build complex rules  :)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

**Test Configuration**:
* PHP version: 8.1
* MySQL version 10.6.5-MariaDB
* Webserver version IIS
* Web browser: MS Edge, Chrome

# Checklist:

- [x] I have read the Contributing documentation available here: https://snipe-it.readme.io/docs/contributing-overview
- [x] I have formatted this PR according to the project guidelines: https://snipe-it.readme.io/docs/contributing-overview#pull-request-guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-11-07 23:17 UTC, spencerrlongg requested changes
Hey Robert, 

Removing the logic in the asset observer means that at the very least the logic needs to be added to the API assets controller. 

The other option would be to remove the logic completely, but then we'd still need to add `eol_explicit` to the API asset controller, as well as get that added to the documentation.

2023-11-08 22:23 UTC, Robert-Azelis commented
Added also logic for API based on `asset_eol_date`, rule is easy if `asset_eol_date` is set, then `eol_explicit` get `true`, otherweis `asset_eol_date` based on asset model rate.

2023-11-29 19:06 UTC, spencerrlongg commented
Hey @Robert-Azelis, I'm working on some changes to the asset store method right now and it's going to cause some conflicts. Hopefully that PR is in today, and then we'll be able to revisit this, sorry for the delay on all this.

2023-11-29 19:17 UTC, spencerrlongg commented
If you want to take a look at it I've got it drafted here: https://github.com/snipe/snipe-it/pull/13964/files

Not quite done but I'll give you a ping when it is.

2023-12-10 10:37 UTC, Robert-Azelis commented
updated `AssetsController.php`, `AssetsControlled.php` for API and `BulkAssetsController.php` to mange `eol_date` when model changed

2024-01-30 12:19 UTC, Robert-Azelis commented
Hi @spencerrlongg any news in this case? I see that new v.6.4 has been published.

2024-01-30 23:35 UTC, spencerrlongg commented
Hey @Robert-Azelis - meant to get back to you a while back but the holidays and stuff got in the way. I think I'm fine with the direction you were going, but unfortunately I ended up refactoring the `store()` method on the API AssetsController so that's created some conflicts, so that'll need to be re-thought. 

I'm planning on applying those same changes to the other AssetsController soon, will probably start on that tomorrow. 

The BulkAssetsController has also undergone some changes. 

I'd be happy to have a look and provide any help if you want to give it another go, though it might be best to wait until I've got the `Assets/AssetsController.php` refactor done.

2024-02-05 07:17 UTC, Robert-Azelis commented
> Hey @Robert-Azelis - meant to get back to you a while back but the holidays and stuff got in the way. I think I'm fine with the direction you were going, but unfortunately I ended up refactoring the `store()` method on the API AssetsController so that's created some conflicts, so that'll need to be re-thought.
> 
> I'm planning on applying those same changes to the other AssetsController soon, will probably start on that tomorrow.
> 
> The BulkAssetsController has also undergone some changes.
> 
> I'd be happy to have a look and provide any help if you want to give it another go, though it might be best to wait until I've got the `Assets/AssetsController.php` refactor done.

Hi @spencerrlongg, I will update files to new code v6.3.0 (try this week), then we can review once again ;)

2024-02-11 11:53 UTC, Robert-Azelis commented
Hi, @spencerrlongg
code has been adapted to new ver. 6.3.0 and created under new PR #14248

2024-02-11 11:53 UTC, closed without merging